name: Cairo 1 programs execution

on:
  push:
    branches: [ main, starkware-development ]
  pull_request:
    branches: [ '**' ]

jobs:
  run:
    name: Execute programs
    runs-on: ubuntu-24.04
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@451ce45ce31d200b52705aadd15ce75018b006de # 1.89.0
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Set up Cargo cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: install corelib
        run:  cd cairo1-run/ && make deps
      - name: Run tests
        run:  cd cairo1-run/ && make test
      - name: Run cairo 1 programs
        run:  cd cairo1-run/ && make run
