name: iai Benchmark

on:
  push:
    branches: [ main, starkware-development ]

jobs:
  cache-iai-results:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@451ce45ce31d200b52705aadd15ce75018b006de # 1.89.0
    - name: Set up cargo cache
      uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
    - name: Install uv
      uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
      with:
        enable-cache: true
    - name: Install python deps
      run: |
          make python-deps
          . cairo-vm-env/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
    - name: Install test dependencies
      run: |
        sudo apt update
        sudo apt install -y valgrind
        IAI_VERSION=$(grep '^iai-callgrind' vm/Cargo.toml | sed 's/.*"\(.*\)"/\1/')
        cargo install --version $IAI_VERSION iai-callgrind-runner

    - name: Run iai benchmarks
      run: make iai-benchmark-action

    - name: Save cache for ${{ github.sha }}
      uses: actions/cache/save@6f8efc29b200d32929f49075959781ed54ec270c # v3
      with:
        path: |
          */target/iai/iai_benchmark/
        key: ${{ runner.os }}-iai-benchmark-cache-${{ github.sha }}
